# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ray.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tray.proto\x12\x06ray.v1\x1a\x1cgoogle/protobuf/struct.proto\">\n\x0eTriggerRequest\x12,\n\x0btask_inputs\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\"@\n\x0fTriggerResponse\x12-\n\x0ctask_outputs\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct2J\n\nRayService\x12<\n\x07Trigger\x12\x16.ray.v1.TriggerRequest\x1a\x17.ray.v1.TriggerResponse\"\x00\x42\rZ\x0b./rayserverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ray_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./rayserver'
  _globals['_TRIGGERREQUEST']._serialized_start=51
  _globals['_TRIGGERREQUEST']._serialized_end=113
  _globals['_TRIGGERRESPONSE']._serialized_start=115
  _globals['_TRIGGERRESPONSE']._serialized_end=179
  _globals['_RAYSERVICE']._serialized_start=181
  _globals['_RAYSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
