# generated by datamodel-codegen:
#   filename:  archetypeai_task_upload_file_input.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Input:
    file: str
