# generated by datamodel-codegen:
#   filename:  base64_task_decode_output.json
#   timestamp: 2024-01-04T22:04:32+00:00

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Output:
    data: str
