# generated by datamodel-codegen:
#   filename:  end_task_end_input.json
#   timestamp: 2024-01-04T22:04:34+00:00

from __future__ import annotations

from typing import Any, Dict

Input = Dict[str, Any]
