# generated by datamodel-codegen:
#   filename:  googlecloudstorage_task_upload_input.json
#   timestamp: 2024-01-04T21:51:28+00:00

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Input:
    data: str
    object_name: str
