# generated by datamodel-codegen:
#   filename:  huggingface_task_table_question_answering_output.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class Output:
    aggregator: Optional[str]
    answer: str
    cells: Optional[List[str]]
    coordinates: Optional[List[List[int]]]


Model = str


@dataclass
class Options:
    use_cache: Optional[bool]
    wait_for_model: Optional[bool]


StringInput = str
