# generated by datamodel-codegen:
#   filename:  huggingface_task_summarization_input.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Options:
    use_cache: Optional[bool] = None
    wait_for_model: Optional[bool] = None


@dataclass
class Parameters:
    max_length: Optional[int] = None
    max_time: Optional[float] = None
    min_length: Optional[int] = None
    repetition_penalty: Optional[float] = None
    temperature: Optional[float] = 1
    top_k: Optional[int] = None
    top_p: Optional[float] = None


@dataclass
class Input:
    inputs: str
    model: Optional[str] = None
    options: Optional[Options] = None
    parameters: Optional[Parameters] = None
