# generated by datamodel-codegen:
#   filename:  huggingface_task_summarization_input.json
#   timestamp: 2024-01-04T21:51:42+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Parameters:
    max_length: Optional[int] = None
    max_time: Optional[float] = None
    min_length: Optional[int] = None
    repetition_penalty: Optional[float] = None
    temperature: Optional[float] = 1
    top_k: Optional[int] = None
    top_p: Optional[float] = None


Model = str


@dataclass
class Options:
    use_cache: Optional[bool] = None
    wait_for_model: Optional[bool] = None


StringInput = str


@dataclass
class Input:
    inputs: StringInput
    model: Optional[Model] = None
    options: Optional[Options] = None
    parameters: Optional[Parameters] = None
