# generated by datamodel-codegen:
#   filename:  huggingface_task_object_detection_input.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

Model = str


@dataclass
class Options:
    use_cache: Optional[bool]
    wait_for_model: Optional[bool]


StringInput = str


@dataclass
class Input:
    image: str
    model: Optional[Model]
