# generated by datamodel-codegen:
#   filename:  huggingface_task_question_answering_input.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Inputs:
    context: str
    question: str


Model = str


@dataclass
class Options:
    use_cache: Optional[bool]
    wait_for_model: Optional[bool]


StringInput = str


@dataclass
class Input:
    inputs: Inputs
    model: Optional[Model]
    options: Optional[Options]
