# generated by datamodel-codegen:
#   filename:  image_task_draw_detection_output.json
#   timestamp: 2024-01-04T22:04:38+00:00

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Output:
    image: str
