# generated by datamodel-codegen:
#   filename:  image_task_draw_semantic_segmentation_input.json
#   timestamp: 2024-01-04T22:04:42+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List, Optional


@dataclass
class Stuff:
    category: str
    rle: str


Stuffs = List[Stuff]


InstillTypes = Any


@dataclass
class Input:
    image: str
    stuffs: Stuffs
    showScore: Optional[bool] = None
