# generated by datamodel-codegen:
#   filename:  instill_task_classification_output.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List


@dataclass
class Output:
    pass


@dataclass
class Classification:
    category: str
    score: float


InstillTypes = Any


@dataclass
class Input:
    image_base64: str
    model_id: str
    model_namespace: str


@dataclass
class Param:
    param_name: str
    param_value: str


ExtraParams = List[Param]
