# generated by datamodel-codegen:
#   filename:  instill_definitions.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional, Union


@dataclass
class InstillModelConnector1:
    mode: Optional[Any] = None


@dataclass
class InstillModelConnector2:
    api_token: str
    server_url: str
    mode: Optional[Any] = None


InstillModelConnector = Union[InstillModelConnector1, InstillModelConnector2]
