# generated by datamodel-codegen:
#   filename:  instill_task_visual_question_answering_output.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Output:
    text: str
