# generated by datamodel-codegen:
#   filename:  openai_task_text_to_image_output.json
#   timestamp: 2024-01-04T21:52:03+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import List


@dataclass
class Result:
    image: str
    revised_prompt: str


@dataclass
class Output:
    results: List[Result]


@dataclass
class ChatMessage:
    content: str
    role: str
