# generated by datamodel-codegen:
#   filename:  openai_task_text_embeddings_input.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, List, Optional


class Model(Enum):
    text_embedding_ada_002 = 'text-embedding-ada-002'


@dataclass
class ImageUrl:
    url: str


class Type(Enum):
    text = 'text'
    image_url = 'image_url'


@dataclass
class MultiModalContentItem:
    type: Type
    image_url: Optional[ImageUrl] = None
    text: Optional[str] = None


InstillTypes = Any


@dataclass
class Input:
    model: Model
    text: str


@dataclass
class ChatMessage:
    content: List[MultiModalContentItem]
    role: str
