# generated by datamodel-codegen:
#   filename:  redis_task_chat_history_retrieve_output.json
#   timestamp: 2024-01-04T21:52:08+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class Message:
    content: str
    role: str
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class Output:
    messages: List[Message]
