# generated by datamodel-codegen:
#   filename:  restapi_task_get_output.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class Input:
    endpoint_path: str
    body: Optional[Dict[str, Any]] = None


@dataclass
class Input1:
    endpoint_path: str


@dataclass
class Output:
    body: Dict[str, Any]
    header: Dict[str, Any]
    status_code: int


Model = Output
