# generated by datamodel-codegen:
#   filename:  restapi_task_patch_output.json
#   timestamp: 2024-01-04T21:52:13+00:00

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional


@dataclass
class InputWithBody:
    endpoint_path: str
    body: Optional[Dict[str, Any]] = None


@dataclass
class InputWithoutBody:
    endpoint_path: str


@dataclass
class Output:
    body: Dict[str, Any]
    header: Dict[str, Any]
    status_code: int


Model = Output
