# generated by datamodel-codegen:
#   filename:  start_task_start_metadata.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional


@dataclass
class Items:
    instillFormat: str
    type: str


@dataclass
class Model1:
    description: Optional[str]
    instillFormat: str
    items: Optional[Items]
    title: Optional[str]
    type: str


Model = Dict[str, Model1]
