# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vdp.connector.v1alpha import connector_definition_pb2 as vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2
from vdp.connector.v1alpha import connector_pb2 as vdp_dot_connector_dot_v1alpha_dot_connector__pb2


class ConnectorPublicServiceStub(object):
    """Connector service responds to external access
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Liveness = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/Liveness',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LivenessRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LivenessResponse.FromString,
                )
        self.Readiness = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/Readiness',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ReadinessRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ReadinessResponse.FromString,
                )
        self.ListConnectorDefinitions = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/ListConnectorDefinitions',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.ListConnectorDefinitionsRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.ListConnectorDefinitionsResponse.FromString,
                )
        self.GetConnectorDefinition = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/GetConnectorDefinition',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.GetConnectorDefinitionRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.GetConnectorDefinitionResponse.FromString,
                )
        self.ListConnectorResources = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/ListConnectorResources',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListConnectorResourcesRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListConnectorResourcesResponse.FromString,
                )
        self.LookUpConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/LookUpConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LookUpConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LookUpConnectorResourceResponse.FromString,
                )
        self.CreateUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/CreateUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.CreateUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.CreateUserConnectorResourceResponse.FromString,
                )
        self.ListUserConnectorResources = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/ListUserConnectorResources',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListUserConnectorResourcesRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListUserConnectorResourcesResponse.FromString,
                )
        self.GetUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/GetUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.GetUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.GetUserConnectorResourceResponse.FromString,
                )
        self.UpdateUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/UpdateUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.UpdateUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.UpdateUserConnectorResourceResponse.FromString,
                )
        self.DeleteUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/DeleteUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DeleteUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DeleteUserConnectorResourceResponse.FromString,
                )
        self.ConnectUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/ConnectUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ConnectUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ConnectUserConnectorResourceResponse.FromString,
                )
        self.DisconnectUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/DisconnectUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DisconnectUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DisconnectUserConnectorResourceResponse.FromString,
                )
        self.RenameUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/RenameUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.RenameUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.RenameUserConnectorResourceResponse.FromString,
                )
        self.ExecuteUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/ExecuteUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ExecuteUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ExecuteUserConnectorResourceResponse.FromString,
                )
        self.WatchUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/WatchUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.WatchUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.WatchUserConnectorResourceResponse.FromString,
                )
        self.TestUserConnectorResource = channel.unary_unary(
                '/vdp.connector.v1alpha.ConnectorPublicService/TestUserConnectorResource',
                request_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.TestUserConnectorResourceRequest.SerializeToString,
                response_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.TestUserConnectorResourceResponse.FromString,
                )


class ConnectorPublicServiceServicer(object):
    """Connector service responds to external access
    """

    def Liveness(self, request, context):
        """///////////////////////////////
        Connector definition methods
        ///////////////////////////////

        Liveness method receives a LivenessRequest message and returns a
        LivenessResponse message.
        See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readiness(self, request, context):
        """Readiness method receives a ReadinessRequest message and returns a
        ReadinessResponse message.
        See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnectorDefinitions(self, request, context):
        """ListConnectorDefinitions method receives a
        ListConnectorDefinitionsRequest message and returns a
        ListConnectorDefinitionsResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectorDefinition(self, request, context):
        """GetConnectorDefinition method receives a
        GetConnectorDefinitionRequest message and returns a
        GetGetConnectorDefinitionResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConnectorResources(self, request, context):
        """///////////////////////////////
        Connector-Resource methods
        ///////////////////////////////

        ListConnectorResources method receives a
        ListConnectorResourcesRequest message and returns a
        ListConnectorResourcesResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookUpConnectorResource(self, request, context):
        """LookUpConnectorResource method receives a
        LookUpConnectorResourceRequest message and returns a
        LookUpConnectorResourceResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserConnectorResource(self, request, context):
        """CreateUserConnectorResource method receives a
        CreateUserConnectorResourceRequest message and returns a
        CreateUserConnectorResourceResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserConnectorResources(self, request, context):
        """ListUserConnectorResources method receives a
        ListUserConnectorResourcesRequest message and returns a
        ListUserConnectorResourcesResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserConnectorResource(self, request, context):
        """GetUserConnectorResource method receives a GetUserConnectorResourceRequest
        message and returns a GetUserConnectorResourceResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserConnectorResource(self, request, context):
        """UpdateUserConnectorResource method receives a
        UpdateUserConnectorResourceRequest message and returns a
        UpdateUserConnectorResourceResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserConnectorResource(self, request, context):
        """DeleteUserConnectorResource method receives a
        DeleteUserConnectorResourceRequest message and returns a
        DeleteUserConnectorResourceResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectUserConnectorResource(self, request, context):
        """Connect a connector resource.
        The "state" of the connector resource after connecting is "CONNECTED".
        ConnectUserConnectorResource can be called on ConnectorResource in the
        state `DISCONNECTED`; ConnectorResource in a different state (including
        `CONNECTED`) returns an error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectUserConnectorResource(self, request, context):
        """Disconnect a connectorResource.
        The "state" of the connectorResource after disconnecting is "DISCONNECTED".
        DisconnectUserConnectorResource can be called on ConnectorResource in the
        state `CONNECTED`; ConnectorResource in a different state (including
        `DISCONNECTED`) returns an error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenameUserConnectorResource(self, request, context):
        """RenameUserConnectorResource method receives a
        RenameUserConnectorResourceRequest message and returns a
        RenameUserConnectorResourceResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteUserConnectorResource(self, request, context):
        """ExecuteUserConnectorResource method receives a
        ExecuteUserConnectorResourceRequest message and returns a
        ExecuteUserConnectorResourceResponse message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchUserConnectorResource(self, request, context):
        """WatchUserConnectorResource method receives a
        WatchUserConnectorResourceRequest message and returns a
        WatchUserConnectorResourceResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestUserConnectorResource(self, request, context):
        """TestUserConnectorResource method receives a TestUserConnectorResourceRequest
        message and returns a TestUserConnectorResourceResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Liveness': grpc.unary_unary_rpc_method_handler(
                    servicer.Liveness,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LivenessRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LivenessResponse.SerializeToString,
            ),
            'Readiness': grpc.unary_unary_rpc_method_handler(
                    servicer.Readiness,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ReadinessRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ReadinessResponse.SerializeToString,
            ),
            'ListConnectorDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectorDefinitions,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.ListConnectorDefinitionsRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.ListConnectorDefinitionsResponse.SerializeToString,
            ),
            'GetConnectorDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectorDefinition,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.GetConnectorDefinitionRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.GetConnectorDefinitionResponse.SerializeToString,
            ),
            'ListConnectorResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConnectorResources,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListConnectorResourcesRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListConnectorResourcesResponse.SerializeToString,
            ),
            'LookUpConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.LookUpConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LookUpConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LookUpConnectorResourceResponse.SerializeToString,
            ),
            'CreateUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.CreateUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.CreateUserConnectorResourceResponse.SerializeToString,
            ),
            'ListUserConnectorResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserConnectorResources,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListUserConnectorResourcesRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListUserConnectorResourcesResponse.SerializeToString,
            ),
            'GetUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.GetUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.GetUserConnectorResourceResponse.SerializeToString,
            ),
            'UpdateUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.UpdateUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.UpdateUserConnectorResourceResponse.SerializeToString,
            ),
            'DeleteUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DeleteUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DeleteUserConnectorResourceResponse.SerializeToString,
            ),
            'ConnectUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ConnectUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ConnectUserConnectorResourceResponse.SerializeToString,
            ),
            'DisconnectUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DisconnectUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DisconnectUserConnectorResourceResponse.SerializeToString,
            ),
            'RenameUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.RenameUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.RenameUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.RenameUserConnectorResourceResponse.SerializeToString,
            ),
            'ExecuteUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ExecuteUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ExecuteUserConnectorResourceResponse.SerializeToString,
            ),
            'WatchUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.WatchUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.WatchUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.WatchUserConnectorResourceResponse.SerializeToString,
            ),
            'TestUserConnectorResource': grpc.unary_unary_rpc_method_handler(
                    servicer.TestUserConnectorResource,
                    request_deserializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.TestUserConnectorResourceRequest.FromString,
                    response_serializer=vdp_dot_connector_dot_v1alpha_dot_connector__pb2.TestUserConnectorResourceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vdp.connector.v1alpha.ConnectorPublicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectorPublicService(object):
    """Connector service responds to external access
    """

    @staticmethod
    def Liveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/Liveness',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LivenessRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LivenessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Readiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/Readiness',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ReadinessRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ReadinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListConnectorDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/ListConnectorDefinitions',
            vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.ListConnectorDefinitionsRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.ListConnectorDefinitionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConnectorDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/GetConnectorDefinition',
            vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.GetConnectorDefinitionRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__definition__pb2.GetConnectorDefinitionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListConnectorResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/ListConnectorResources',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListConnectorResourcesRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListConnectorResourcesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LookUpConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/LookUpConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LookUpConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.LookUpConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/CreateUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.CreateUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.CreateUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUserConnectorResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/ListUserConnectorResources',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListUserConnectorResourcesRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ListUserConnectorResourcesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/GetUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.GetUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.GetUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/UpdateUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.UpdateUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.UpdateUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/DeleteUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DeleteUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DeleteUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/ConnectUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ConnectUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ConnectUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/DisconnectUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DisconnectUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.DisconnectUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenameUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/RenameUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.RenameUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.RenameUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/ExecuteUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ExecuteUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.ExecuteUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/WatchUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.WatchUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.WatchUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestUserConnectorResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vdp.connector.v1alpha.ConnectorPublicService/TestUserConnectorResource',
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.TestUserConnectorResourceRequest.SerializeToString,
            vdp_dot_connector_dot_v1alpha_dot_connector__pb2.TestUserConnectorResourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
