"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import grpc
import grpc.aio
import typing
import vdp.connector.v1alpha.connector_definition_pb2
import vdp.connector.v1alpha.connector_pb2

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class ConnectorPrivateServiceStub:
    """Connector service responds to internal access"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    LookUpConnectorDefinitionAdmin: grpc.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_definition_pb2.LookUpConnectorDefinitionAdminRequest,
        vdp.connector.v1alpha.connector_definition_pb2.LookUpConnectorDefinitionAdminResponse,
    ]
    """LookUpConnectorDefinitionAdmin method receives a
    LookUpConnectorDefinitionAdminRequest message and returns a
    LookUpConnectorDefinitionAdminResponse
    """
    ListConnectorResourcesAdmin: grpc.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_pb2.ListConnectorResourcesAdminRequest,
        vdp.connector.v1alpha.connector_pb2.ListConnectorResourcesAdminResponse,
    ]
    """ListConnectorResourcesAdmin method receives a ListConnectorResourcesAdminRequest
    message and returns a ListConnectorResourcesResponse message.
    """
    LookUpConnectorResourceAdmin: grpc.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_pb2.LookUpConnectorResourceAdminRequest,
        vdp.connector.v1alpha.connector_pb2.LookUpConnectorResourceAdminResponse,
    ]
    """LookUpConnectorResourceAdmin method receives a
    LookUpConnectorResourceAdminRequest message and returns a
    LookUpConnectorResourceAdminResponse
    """
    CheckConnectorResource: grpc.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_pb2.CheckConnectorResourceRequest,
        vdp.connector.v1alpha.connector_pb2.CheckConnectorResourceResponse,
    ]
    """CheckConnectorResource method receives a CheckConnectorResourceRequest message and returns a
    CheckConnectorResourceResponse
    """

class ConnectorPrivateServiceAsyncStub:
    """Connector service responds to internal access"""

    LookUpConnectorDefinitionAdmin: grpc.aio.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_definition_pb2.LookUpConnectorDefinitionAdminRequest,
        vdp.connector.v1alpha.connector_definition_pb2.LookUpConnectorDefinitionAdminResponse,
    ]
    """LookUpConnectorDefinitionAdmin method receives a
    LookUpConnectorDefinitionAdminRequest message and returns a
    LookUpConnectorDefinitionAdminResponse
    """
    ListConnectorResourcesAdmin: grpc.aio.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_pb2.ListConnectorResourcesAdminRequest,
        vdp.connector.v1alpha.connector_pb2.ListConnectorResourcesAdminResponse,
    ]
    """ListConnectorResourcesAdmin method receives a ListConnectorResourcesAdminRequest
    message and returns a ListConnectorResourcesResponse message.
    """
    LookUpConnectorResourceAdmin: grpc.aio.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_pb2.LookUpConnectorResourceAdminRequest,
        vdp.connector.v1alpha.connector_pb2.LookUpConnectorResourceAdminResponse,
    ]
    """LookUpConnectorResourceAdmin method receives a
    LookUpConnectorResourceAdminRequest message and returns a
    LookUpConnectorResourceAdminResponse
    """
    CheckConnectorResource: grpc.aio.UnaryUnaryMultiCallable[
        vdp.connector.v1alpha.connector_pb2.CheckConnectorResourceRequest,
        vdp.connector.v1alpha.connector_pb2.CheckConnectorResourceResponse,
    ]
    """CheckConnectorResource method receives a CheckConnectorResourceRequest message and returns a
    CheckConnectorResourceResponse
    """

class ConnectorPrivateServiceServicer(metaclass=abc.ABCMeta):
    """Connector service responds to internal access"""

    @abc.abstractmethod
    def LookUpConnectorDefinitionAdmin(
        self,
        request: vdp.connector.v1alpha.connector_definition_pb2.LookUpConnectorDefinitionAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[vdp.connector.v1alpha.connector_definition_pb2.LookUpConnectorDefinitionAdminResponse, collections.abc.Awaitable[vdp.connector.v1alpha.connector_definition_pb2.LookUpConnectorDefinitionAdminResponse]]:
        """LookUpConnectorDefinitionAdmin method receives a
        LookUpConnectorDefinitionAdminRequest message and returns a
        LookUpConnectorDefinitionAdminResponse
        """
    @abc.abstractmethod
    def ListConnectorResourcesAdmin(
        self,
        request: vdp.connector.v1alpha.connector_pb2.ListConnectorResourcesAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[vdp.connector.v1alpha.connector_pb2.ListConnectorResourcesAdminResponse, collections.abc.Awaitable[vdp.connector.v1alpha.connector_pb2.ListConnectorResourcesAdminResponse]]:
        """ListConnectorResourcesAdmin method receives a ListConnectorResourcesAdminRequest
        message and returns a ListConnectorResourcesResponse message.
        """
    @abc.abstractmethod
    def LookUpConnectorResourceAdmin(
        self,
        request: vdp.connector.v1alpha.connector_pb2.LookUpConnectorResourceAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[vdp.connector.v1alpha.connector_pb2.LookUpConnectorResourceAdminResponse, collections.abc.Awaitable[vdp.connector.v1alpha.connector_pb2.LookUpConnectorResourceAdminResponse]]:
        """LookUpConnectorResourceAdmin method receives a
        LookUpConnectorResourceAdminRequest message and returns a
        LookUpConnectorResourceAdminResponse
        """
    @abc.abstractmethod
    def CheckConnectorResource(
        self,
        request: vdp.connector.v1alpha.connector_pb2.CheckConnectorResourceRequest,
        context: _ServicerContext,
    ) -> typing.Union[vdp.connector.v1alpha.connector_pb2.CheckConnectorResourceResponse, collections.abc.Awaitable[vdp.connector.v1alpha.connector_pb2.CheckConnectorResourceResponse]]:
        """CheckConnectorResource method receives a CheckConnectorResourceRequest message and returns a
        CheckConnectorResourceResponse
        """

def add_ConnectorPrivateServiceServicer_to_server(servicer: ConnectorPrivateServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
